backend/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("catalog/", include("goods.urls", namespace="goods")),
    path('user/', include("users.urls", namespace="user")),
    path("cart/", include("carts.urls", namespace="cart")),
    path("orders/", include("orders.urls", namespace="orders")),
]

if settings.DEBUG is True:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),        
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/goods/urls.py
from django.urls import path
from . import views


app_name = "goods"

urlpatterns = [
    path("search/", views.catalog, name="search"),    
    path("<slug:category_slug>/", views.catalog, name="catalog"),    
    path("product/<int:product_id>/", views.product, name="product"),
    path("product/<slug:product_slug>/", views.product, name="product"),
]

backend/main/urls.py
from django.urls import path
from . import views


app_name = "main"

urlpatterns = [
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("pay_and_delivery/", views.pay_and_delivery, name="pay-and-delivery"),
    path("information/", views.information, name="information"),
]

backend/users/urls.py
from django.urls import path
from . import views


app_name = "user"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("registration/", views.registration, name="registration"),
    path("profile/", views.profile, name="profile"),
    path("user-cart/", views.users_cart, name="user-cart"),
    path("logout/", views.logout, name="logout"),
]

backend/templates/includes/cart_modal.html
{% load static %}

{% load carts_tags %}

{% user_carts request as carts %}

<div>
    <button type="button" class="btn btn-dark btn-secondary d-flex" id="modalButton"
        aria-expanded="false">
        <img class="mx-1" src="{% static "deps/icons/basket2-fill.svg" %}" alt="Catalog Icon" width="24"
            height="24">
        <span id="goods-in-cart-count">{{ carts.total_quantity }}</span>
    </button>
</div>
<!-- Разметка модального окна корзины -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="btn-close" data-bs-dismiss="modal"
                    aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <h3 class="text-center mb-4">Корзина</h3>
                <div class="container" id="cart-items-container">
                    <!-- Разметка корзины -->
                    {% include "carts/includes/included_cart.html" %}
                    <!-- Закончилась разметка корзины -->
                </div>
            </div>
        </div>
    </div>
</div>

backend/templates/includes/include_header.html
{% load static %}

<nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
    <div class="container">
        <a class="navbar-brand" href="{% url "main:index" %}">Главная</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown ">
                    <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Справочная информация
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item  text-white" href="{% url 'main:pay-and-delivery' %}">Доставка и оплата</a></li>
                        <li><a class="dropdown-item  text-white" href="{% url "main:about" %}">О нас</a></li>
                        <li><a class="dropdown-item  text-white" href="{% url "main:information" %}">Контактная информация</a></li>                                
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link  text-white" href="{% url "user:user-cart"%}">Корзина</a>
                </li>
                {% if not user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link  text-white" href="{% url "user:login" %}">Войти</a>
                </li>
                {% else %}
                    <li class="nav-item dropdown ">
                        <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Мой профиль
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item  text-white" href="{% url "user:user-cart"%}">Корзина</a></li>
                            <li><a class="dropdown-item  text-white" href="{% url "user:profile" %}">Личный кабинет</a>
                            </li>
                            {% if user.is_admin or user.is_staff %}
                                <li><a class="dropdown-item  text-white" href="{% url "admin:index" %}">Админ панель</a></li>                                    
                            {% endif %}
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item  text-white" href="{% url "user:logout" %}">Выйти</a></li>
                        </ul>
                    </li>                        
                {% endif %}
            </ul>
            <form class="d-flex" role="search" action="{% url "goods:search" %}" method="get">
                <input class="form-control me-2" type="search" name="q" placeholder="Поиск" aria-label="Search">
                <button class="btn btn-outline-success text-white" type="submit">Поиск</button>
            </form>
        </div>
    </div>
</nav>

backend/templates/includes/notifications.html
{% load static %}

{% if form.non_field_errors %}
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="alert alert-danger alert-dismissible fade show custom-shadow" role="alert">
                {{ form.non_field_errors }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        </div>
    </div>
</div>
{% endif %}

<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-6">
            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'success' %}
                    <div id="notification" class="position-fixed start-50 translate-middle-x z-3 alert alert-success fade show custom-shadow" role="alert">
                        {{ message }}
                    </div>
                    {% endif %}
                    {% if message.tags == 'warning' %}
                    <div id="notification" class="position-fixed start-50 translate-middle-x z-3 alert alert-danger fade show custom-shadow" role="alert">
                        {{ message }}
                    </div>
                    {% endif %}
                {% endfor %}
            {% else %}
            <div id="jq-notification" class="position-fixed start-50 translate-middle-x z-3 alert alert-success fade show custom-shadow" style="display: none;" role="alert">
            </div>
            {% endif %}
        </div>
    </div>
</div>