backend/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("catalog/", include("goods.urls", namespace="goods")),
    path('user/', include("users.urls", namespace="user")),
    path("cart/", include("carts.urls", namespace="cart")),
    path("orders/", include("orders.urls", namespace="orders")),
]

if settings.DEBUG is True:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),        
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/orders/urls.py
from django.urls import path
from . import views


app_name = "orders"

urlpatterns = [
    path("create-order/", views.create_order, name="create-order"),

]

backend/orders/models.py
from django.db import models

from goods.models import Products
from users.models import User


class Order(models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.SET_DEFAULT,
        default=None,
        verbose_name="Пользователь",
        blank=True,
        null=True,
    )
    created_timestamp = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата и время создания заказа"
    )
    phone_number = models.CharField(max_length=20, verbose_name="Номер телефона")
    delivery_address = models.TextField(
        null=True, blank=True, verbose_name="Адрес доставки"
    )
    requires_delivery = models.BooleanField(
        default=False, verbose_name="Необходимость доставки?"
    )
    payment_on = models.BooleanField(
        default=False, verbose_name="Оплата при получении?"
    )

    is_paid = models.BooleanField(default=False, verbose_name="Оплачен?")

    status = models.CharField(
        max_length=32,
        default="В обработке",
        verbose_name="Статус заказа",
    )

    class Meta:
        db_table = "order"
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"
        ordering = ["-created_timestamp"]

    def __str__(self):
        return f"Заказ No{self.id} | Покупатель {self.user.email}"


class OrderItemsQuerySet(models.QuerySet):
    def get_total_price(self):
        return sum(item.products_price() for item in self)
    
    def total_quantity(self):
        if self:
            return sum(item.quantity for item in self)
        return 0


class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name="Заказ")
    product = models.ForeignKey(
        to=Products,
        on_delete=models.SET_DEFAULT,
        null=True,
        default=None,
        verbose_name="Продукт",
    )
    name = models.CharField(max_length=128, verbose_name="Наименование")
    price = models.DecimalField(
        max_digits=8, decimal_places=2, verbose_name="Стоимость"
    )
    quantity = models.PositiveIntegerField(default=0, verbose_name="Количество")
    created_timestamp = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата и время продажи"
    )
    objects = OrderItemsQuerySet.as_manager()

    class Meta:
        db_table = "order_item"
        verbose_name = "Товар в заказе"
        verbose_name_plural = "Товары в заказе"
        ordering = ["-created_timestamp"]
    
    def products_price(self):
        return round(self.price * self.quantity, 2)
    
    def __str__(self):
        return f"Заказ No{self.order.id} | Товар: {self.name}"

backend/orders/forms.py
# class CreateOrderForm(forms.Form):
#     first_name = forms.CharField(
#         widget=forms.TextInput(
#             attrs={
#                 "class": "form-control",
#                 "placeholder": "Введите Ваше имя",
#             }
#         )
#     )
#     last_name = forms.CharField(
#         widget=forms.TextInput(
#             attrs={
#                 "class": "form-control",
#                 "placeholder": "Введите Вашу фамилию",
#             }
#         )
#     )
#     phone_number = forms.CharField(
#         widget=forms.TextInput(
#             attrs={
#                 "class": "form-control",
#                 "placeholder": "Актуальный номер телефона",
#             }
#         )
#     )
#     delivery_address = forms.CharField(        
#         widget=forms.Textarea(
#             attrs={
#                 "class": "form-control",
#                 "id": "delivery_address",
#                 "rows": 2,
#                 "placeholder": "Желаемый адрес доставки",
#             }
#         )
#     )
#     requires_delivery = forms.ChoiceField(
#         widget=forms.RadioSelect(),
#         choices=[
#             ("0", False),
#             ("1", True),
#         ],
#         initial=0,
#     )
#     payment_on = forms.ChoiceField(
#         widget=forms.RadioSelect(),
#         choices=[
#             ("0", False),
#             ("1", True),
#             ],
#         initial=0,
#     )
#  front use in back
import re
from django import forms


class CreateOrderForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    phone_number = forms.CharField()
    delivery_address = forms.CharField(required=False)
    requires_delivery = forms.ChoiceField(choices=[
                     ("0", False),
                     ("1", True),
                    ],)
    payment_on = forms.ChoiceField(choices=[
             ("0", False),
             ("1", True),
             ],)
    
    def clear_phone_number(self):
        phone_number = self.cleaned_data["phone_number"]
        phone_number = phone_number.replace("-", "").replace(" ", "")
        if not phone_number.isdigit():
            raise forms.ValidationError("Номер телефона должен содержать только цифры")        
        pattern = re.compile(r'^\d{10}$')
        if not pattern.match(phone_number):
            raise forms.ValidationError("Неверный формат телефонного номера")
        return phone_number


    

backend/orders/views.py
from django.contrib import messages
from django.db import transaction
from django.forms import ValidationError
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required

from carts.models import Cart
from orders.models import Order, OrderItem
from .forms import CreateOrderForm

@login_required
def create_order(request):
    context = {}

    if request.method == "POST":
        form = CreateOrderForm(data=request.POST)
        if form.is_valid():
            try:
                with transaction.atomic():
                    user = request.user
                    cart_items = Cart.objects.filter(user=user)
                    if cart_items.exists():
                        order = Order.objects.create(
                            user=user,
                            phone_number=form.cleaned_data["phone_number"],
                            delivery_address=form.cleaned_data["delivery_address"],
                            requires_delivery=form.cleaned_data["requires_delivery"],
                            payment_on=form.cleaned_data["payment_on"],
                        )
                        for cart_item in cart_items:
                            product = cart_item.product
                            name = cart_item.product.name
                            price = cart_item.product.get_sell_price()
                            quantity = cart_item.quantity

                            if product.quantity < quantity:
                                raise ValidationError(f"Недостаточное количество товара: {name} в наличии на складе")
                            
                            OrderItem.objects.create(
                                order=order,
                                product=product,
                                name=name,
                                price=price,
                                quantity=quantity,
                            )
                            product.quantity -= quantity
                            product.save()
                        
                        cart_items.delete()

                        messages.success(request, "Заказ успешно оформлен, корзина обновлена!")
                        return redirect("user:profile")
            except ValidationError as err:
                messages.info(request, str(err))                
                return redirect("user:profile")   
    else:
        initial = {
            "first_name": request.user.first_name,
            "last_name": request.user.last_name,            
        }
        form = CreateOrderForm(initial=initial)

    context.update({
        "title": 'Оформление заказа',
        "form": form,
    })
    return render(request, "orders/create_order.html", context=context)

backend/orders/templates/orders/create_order.html
{% extends "base.html" %}

{% load static %}
{% load carts_tags %}


{% block content %}
<div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
    <div class="container">
        <h3 class="text-center mb-4">Выбранные товары</h3>
        <div class="container" id="cart-items-container">
            <!-- Разметка корзины -->
            {% user_carts request as carts %}

            {% include "carts/includes/included_cart.html" %}
            <!-- Закончилась разметка корзины -->
        </div>
    </div>
    <!-- Детали заказа -->
    <div class="container">
        <h3 class="text-center">Детали заказа</h3>
        <div class="card mb-3">
            <div class="card-body">
                <form action="{% url "orders:create-order" %}" method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="id_first_name" class="form-label">Ваше имя*:</label>
                            <input type="text" class="form-control" id="id_first_name"
                            value="{% if form.first_name.value %}{{ form.first_name.value }}{% else %}{% endif %}"
                            name="first_name" required>
                            {% if form.first_name.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
                            {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_last_name" class="form-label">Ваша фамилия*:</label>
                            <input type="text" class="form-control" id="id_last_name" 
                            value="{% if form.last_name.value %}{{ form.last_name.value }}{% else %}{% endif %}"
                            name="last_name" required>
                            {% if form.last_name.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
                            {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_phone_number" class="form-label">Номер телефона*:</label>
                            <input type="text" class="form-control" id="id_phone_number" name="phone_number"
                                placeholder="В формате: XXX-XXX-XX-XX"
                                value="{% if form.phone_number.value %}{{ form.firsform.phone_number.value }}{% else %}{% endif %}"
                                required>
                                {% if form.phone_number.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.phone_number.errors }}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-12 mb-3">
                            <label for="delivery" class="form-label">Способ доставки: </label>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="requires_delivery"
                                    id="id_requires_delivery" value="1" checked>
                                <label class="form-check-label" for="id_requires_delivery">Нужна
                                    доставка?</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="requires_delivery"
                                    id="id_requires_delivery" value="0">
                                <label class="form-check-label" for="id_requires_delivery">Самовывоз</label>
                            </div>
                        </div>
                        <div class="mb-3" id="deliveryAddressField">
                            <label for="id_delivery_address" class="form-label">Адрес
                                доставки*:</label>
                            <textarea class="form-control" id="id_delivery_address"
                            value="{% if form.delivery_address.value %}{{ form.delivery_address.value }}{% else %}{% endif %}"
                                name="delivery_address" rows="2"></textarea>
                                {% if form.delivery_address.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.delivery_address.errors }}</div>
                                {% endif %}
                        </div>
                        <div class="col-md-12 mb-3">
                            <label class="form-label">Способ оплаты: </label>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="payment_on"
                                    id="id_payment_on" value="0" checked>
                                <label class="form-check-label" for="id_payment_on">Оплата
                                    картой</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="payment_on"
                                    id="id_payment_on" value="1">
                                <label class="form-check-label" for="id_payment_on">Наличными/картой
                                    при плучении</label>
                                    {% if form.payment_on.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.payment_on.errors }}</div>
                                    {% endif %}
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-dark">Оформить заказ</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock content %}